# Generated by Django 3.1.6 on 2022-03-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220321_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
