# Generated by Django 3.1.6 on 2022-03-27 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myapp', '0004_connectionnode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='items',
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbox_item_type', models.CharField(choices=[('like', 'like'), ('post', 'post'), ('comment', 'comment'), ('friendfollowrequest', 'friendfollowrequest')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('item_id', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.inbox')),
            ],
        ),
    ]
